cmake_minimum_required(VERSION 3.16)
project(r4_gazebo_comparison)
find_package(ament_cmake REQUIRED)
foreach(p rclcpp nav2_core nav2_costmap_2d pluginlib tf2_ros tf2 std_msgs rm_r4_prediction_consumption)
 find_package(${p} REQUIRED)
endforeach()
add_library(research_controller SHARED controller.cpp)
target_compile_features(research_controller PUBLIC cxx_std_17)
target_compile_options(research_controller PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(research_controller rclcpp nav2_core nav2_costmap_2d pluginlib tf2_ros tf2 std_msgs)
target_link_libraries(research_controller rm_r4_prediction_consumption::rm_r4_prediction_consumption_follow)
pluginlib_export_plugin_description_file(nav2_core plugin.xml)
install(TARGETS research_controller LIBRARY DESTINATION lib)
ament_package()
