cmake_minimum_required(VERSION 3.16)
project(rm_dynamic_prediction_critic LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(ament_cmake REQUIRED)
find_package(nav2_mppi_controller REQUIRED)
find_package(nav2_costmap_2d REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rm_competition_interfaces REQUIRED)
add_library(rm_dynamic_prediction_critic SHARED src/prediction_critic.cpp)
target_include_directories(rm_dynamic_prediction_critic PUBLIC include)
ament_target_dependencies(rm_dynamic_prediction_critic nav2_mppi_controller nav2_costmap_2d pluginlib rclcpp rm_competition_interfaces)
pluginlib_export_plugin_description_file(nav2_mppi_controller critics.xml)
install(TARGETS rm_dynamic_prediction_critic LIBRARY DESTINATION lib)
install(DIRECTORY include/ DESTINATION include)
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_geometry test/test_geometry.cpp)
  target_include_directories(test_geometry PRIVATE include)
endif()
ament_package()
