octomap_server:
  ros__parameters:
    frame_id: map
    base_frame_id: base_link
    resolution: 0.05
    sensor_model.max_range: 12.0
    sensor_model.hit: 0.70
    sensor_model.miss: 0.40
    sensor_model.min: 0.12
    sensor_model.max: 0.97
    point_cloud_min_z: -0.30
    point_cloud_max_z: 2.50
    occupancy_min_z: 0.10
    occupancy_max_z: 1.80
    filter_ground_plane: false
    filter_speckles: true
    compress_map: true
    incremental_2D_projection: false
    publish_free_space: false
    latch: true
