cmake_minimum_required(VERSION 3.8)
project(costmap_mask_probe_cpp)
find_package(ament_cmake REQUIRED)
find_package(nav2_costmap_2d REQUIRED)
find_package(geometry_msgs REQUIRED)
add_executable(costmap_mask_probe src/costmap_mask_probe.cpp)
ament_target_dependencies(costmap_mask_probe nav2_costmap_2d geometry_msgs)
install(TARGETS costmap_mask_probe DESTINATION lib/${PROJECT_NAME})
ament_package()
