cmake_minimum_required(VERSION 3.8)
project(rm_temporal_mpc_controller)
set(CMAKE_CXX_STANDARD 17)
add_compile_options(-Wall -Wextra -Wpedantic)
find_package(ament_cmake REQUIRED)
foreach(dep nav2_core nav2_costmap_2d rclcpp rclcpp_lifecycle pluginlib tf2 tf2_ros tf2_geometry_msgs nav_msgs std_msgs rm_competition_interfaces rm_temporal_mpc_msgs)
  find_package(${dep} REQUIRED)
endforeach()
add_library(temporal_mpc_controller SHARED src/controller.cpp)
ament_target_dependencies(temporal_mpc_controller nav2_core nav2_costmap_2d rclcpp rclcpp_lifecycle pluginlib tf2 tf2_ros tf2_geometry_msgs nav_msgs std_msgs rm_competition_interfaces rm_temporal_mpc_msgs)
pluginlib_export_plugin_description_file(nav2_core plugins.xml)
install(TARGETS temporal_mpc_controller LIBRARY DESTINATION lib)
ament_package()
